from django.contrib import admin
from django.urls import path, include
from home import views
urlpatterns = [
    path("contact/",views.contact,name='contact'),
    path("", views.index, name='home'),
    path("about/",views.about,name='about'),
    path("services/",views.services,name='services'),
    path('icecream/',views.ice,name='icecream'),
    #path('handlelogin',views.softy,name='softy'),
    path('family',views.family,name='family'),
    path('register',views.register,name="register"),
    path('buy_butterscotch_cup/',views.buy_butterscotch_cup,name='buy_butterscotch_cup'),
    path('details/',views.detail,name="details"),
    path('buy_chocolate_capucino',views.buy_chocolate_capucino,name="buy_chocolate_capucino"),
    path('buy_vanilla_royale',views.buy_vanilla_royale,name="buy_vanilla_royale"),
    path('buy_chocolate_brownie',views.buy_chocolate_brownie,name="buy_chocolate_brownie"),
    path('buy_chocolate_fudge',views.buy_chocolate_fudge,name="buy_chocolate_fudge"),
    path('details/submit',views.Details,name="details/submit"),
    path('buy_creamy_almond',views.buy_creamy_almond,name="buy_creamy_almond"),
    path('buy_roasted_almond',views.buy_roasted_almond,name="buy_roasted_almond"),
    path('buy_morocon',views.buy_morocon,name="buy_morocon"),
    path('buy_butterscotch_tricone',views.buy_butterscotch_tricone,name="buy_butterscotch_tricone"),
    path('butterscotch_tricone',views.Details_,name="Details_"),
    path('brownie', views.Details_2, name="Details_2"),
    path('capucinox', views.Details_3, name="Details_3"),
    path('fudge', views.Details_4, name="Details_4"),
    path('creamy_almond', views.Details_5, name="Details_5"),
    path('morocon', views.Details_6, name="Details_6"),
    path('roasted_almond', views.Details_7, name="Details_7"),
    path('vanilla_royale', views.Details_8, name="Details_8"),
    path('vr',views.vr,name="vr"),
    path('bt', views.bt, name="bt"),
    path('cb', views.cb, name="cb"),
    path('cc', views.cc, name="cc"),
    path('cf', views.cf, name="cf"),
    path('ca', views.ca, name="ca"),
    path('m', views.m, name="m"),
    path('ra', views.ra,name="ra"),

]