# Generated by Django 3.2.6 on 2021-08-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_contact_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='lgin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMAIL', models.EmailField(max_length=122)),
                ('Password', models.CharField(max_length=18)),
            ],
        ),
    ]
