# Generated by Django 3.2.6 on 2021-08-18 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_lgin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='desc',
        ),
    ]
